version: "3.9"  # optional since v1.27.0
services:
  api:
    build: ../WebApi/.
    depends_on:
      - redis
      - db

  redis:
    image: redis
    volumes:
        - ../cache:/data
    restart: always
    ports:
      - '6379:6379'

  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - ../pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
        - db